src/Web/Areas/Admin/Models/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.Models
{
    public class DashboardViewModel
    {
        public int CategoryCount { get; set; }
        public int StyleCount { get; set; }
        public int BrandCount { get; set; }
        public int ProductCount { get; set; }
        public int UserCount { get; set; }
        public int OrderCount { get; set; }
        //public int CommentCount { get; set; }

    }
}

src/Web/Areas/Admin/Controllers/BrandsController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.Controllers
{
    public class BrandsController : AdminBaseController
    {
        private readonly IRepository<Brand> _brandRepository;

        public BrandsController(IRepository<Brand> brandRepository)
        {
            _brandRepository = brandRepository;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _brandRepository.ListAllAsync());
        }
        public async Task<IActionResult> New()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> New(string name)
        {
            Brand brand = new Brand()
            {
                Name = name,
            };
            await _brandRepository.AddAsync(brand);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var brand = await _brandRepository.GetByIdAsync(id);
            if (brand == null) return NotFound();
            await _brandRepository.DeleteAsync(brand);
            return RedirectToAction(nameof(Index), new { message = "deleted" });
        }
        public async Task<IActionResult> Edit(int id)
        {
            var brand = await _brandRepository.GetByIdAsync(id);
            if (brand == null) return NotFound();
            return View(brand);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Brand brand)
        {
            var brandTobeEdited = await _brandRepository.GetByIdAsync(brand.Id);
            if (brandTobeEdited == null) return NotFound();
            brandTobeEdited.Name = brand.Name;
            await _brandRepository.UpdateAsync(brandTobeEdited);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Web/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Admin.Interfaces;

namespace Web.Areas.Admin.Controllers
{
    public class DashboardController : AdminBaseController
    {
        private readonly IDashboardViewModelService _dashboardViewModelService;

        public DashboardController(IDashboardViewModelService dashboardViewModelService)
        {
            _dashboardViewModelService = dashboardViewModelService;
        }
        public async Task<IActionResult> Index()
        { 
            return View(await _dashboardViewModelService.GetDashboardViewModelAsync());
        }
    }
}

src/Web/Areas/Admin/Controllers/OrdersController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Admin.Interfaces;

namespace Web.Areas.Admin.Controllers
{
    public class OrdersController : AdminBaseController
    {
        private readonly IOrdersViewModelService _ordersViewModelService;

        public OrdersController(IOrdersViewModelService ordersViewModelService)
        {
            _ordersViewModelService = ordersViewModelService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _ordersViewModelService.GetOrderViewModelAsync());
        }
    }
}

src/Web/Areas/Admin/Controllers/ProductsController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Admin.Interfaces;
using Web.Areas.Admin.Models;
using Web.Areas.Admin.Services;

namespace Web.Areas.Admin.Controllers
{
    public class ProductsController : AdminBaseController
    {
        private readonly IProductsViewModelService _productsViewModelService;
        private readonly INewProductViewModelService _newProductViewModelService;
        private readonly IRepository<Product> _productRepository;
        private readonly IWebHostEnvironment _env;
        private readonly PhotoService _photoService;
        private readonly IEditProductViewModelService _editProductViewModelService;

        public ProductsController(IProductsViewModelService productsViewModelService,INewProductViewModelService newProductViewModelService,
            IRepository<Product> productRepository, IWebHostEnvironment env, PhotoService photoService, IEditProductViewModelService editProductViewModelService)
        {
            _productsViewModelService = productsViewModelService;
            _newProductViewModelService = newProductViewModelService;
            _productRepository = productRepository;
            _env = env;
            _photoService = photoService;
            _editProductViewModelService = editProductViewModelService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _productsViewModelService.GetProductsViewModelAsync());
        }

        [HttpPost,ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null) return NotFound();
            _photoService.DeletePhoto(product.PictureUri);
            await _productRepository.DeleteAsync(product);
            return RedirectToAction("Index", new {message = "deleted"});
        }

        public async Task<IActionResult> New()
        {
            return View(await _newProductViewModelService.GetNewProductViewModelAsync());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> New(NewProductViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Product product = new Product()
                {
                    BrandId = (int)vm.BrandId,
                    CategoryId = (int)vm.CategoryId,
                    StyleId = (int)vm.StyleId,
                    Description = vm.ProductDescription,
                    DiscountRate = (int)vm.ProductDiscountRate,
                    Name = vm.ProductName,
                    Price = (decimal)vm.ProductPrice,  
                    PictureUri = _photoService.SavePhoto(vm.ProductImage),
                    SalesQuantity = (int)vm.ProductSalesQuantity,
                    StockQuantity = (int)vm.ProductStockQuantity,
                };
                await _productRepository.AddAsync(product);
                return RedirectToAction(nameof(Index));
            }
            return View(await _newProductViewModelService.GetNewProductViewModelAsync());
        }

        public async Task<IActionResult> Edit(int id)
        {
            var editProductViewModel = await _editProductViewModelService.GetEditProductViewModelAsync(id);
            if (editProductViewModel == null) return NotFound();
            return View(editProductViewModel);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditProductViewModel vm)
        {
            var product = await _productRepository.GetByIdAsync(vm.Id);
            if (product == null) return NotFound();

            if (ModelState.IsValid)
            {
                product.Name = vm.ProductName;
                product.Description = vm.ProductDescription;
                product.Price = (decimal)vm.ProductPrice;
                if (vm.ProductImage != null)
                {
                    _photoService.DeletePhoto(vm.ProductPictureUri);
                    product.PictureUri = _photoService.SavePhoto(vm.ProductImage);
                }
                product.CategoryId = (int)vm.CategoryId;
                product.BrandId = (int)vm.BrandId;
                product.StyleId = (int)vm.StyleId;
                product.CreatedTime = DateTime.Now;
                product.DiscountRate = (int)vm.ProductDiscountRate;
                product.SalesQuantity = (int)vm.ProductSalesQuantity;
                product.StockQuantity = (int)vm.ProductStockQuantity;
                 
                await _productRepository.UpdateAsync(product);

                return RedirectToAction(nameof(Index));
            }
            return View(vm);
        }
    }
}

src/Web/Areas/Admin/Controllers/StylesController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Admin.Controllers
{
    public class StylesController : AdminBaseController
    {
        private readonly IRepository<Style> _styleRepository;

        public StylesController(IRepository<Style> styleRepository)
        {
            _styleRepository = styleRepository;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _styleRepository.ListAllAsync());
        }
        public async Task<IActionResult> New()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> New(string name)
        {
            Style style = new Style()
            {
                Name = name,
            };
            await _styleRepository.AddAsync(style);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var style = await _styleRepository.GetByIdAsync(id);
            if (style == null) return NotFound();
            await _styleRepository.DeleteAsync(style);
            return RedirectToAction(nameof(Index), new { message = "deleted" });
        }
        public async Task<IActionResult> Edit(int id)
        {
            var style = await _styleRepository.GetByIdAsync(id);
            if (style == null) return NotFound();
            return View(style);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Brand brand)
        {
            var styleTobeEdited = await _styleRepository.GetByIdAsync(brand.Id);
            if (styleTobeEdited == null) return NotFound();
            styleTobeEdited.Name = brand.Name;
            await _styleRepository.UpdateAsync(styleTobeEdited);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/Web/Areas/Admin/Views/Dashboard/Index.cshtml
@model DashboardViewModel
@{
    ViewData["Title"] = "Dashboard";
}

<!-- Small boxes (Stat box) -->
<div class="row">
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-danger">
            <div class="inner">
                <h3>@Model.ProductCount</h3>

                <p>Products</p>
            </div>
            <div class="icon">
                <i class="ion ion-folder"></i>
            </div>
            <a asp-controller="Products" asp-action="Index" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h3>@Model.CategoryCount@*<sup style="font-size: 20px">%</sup>*@</h3>

                <p>Categories</p>
            </div>
            <div class="icon">
                <i class="ion ion-folder"></i>
            </div>
            <a asp-controller="Categories" asp-action="Index" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>@Model.BrandCount</h3>

                <p>Brands</p>
            </div>
            <div class="icon">
                <i class="ion ion-folder"></i>
            </div>
            <a asp-controller="Brands" asp-action="Index" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-blue">
            <div class="inner">
                <h3>@Model.StyleCount</h3>

                <p>Styles</p>
            </div>
            <div class="icon">
                <i class="ion ion-folder"></i>
            </div>
            <a asp-controller="Styles" asp-action="Index" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-orange">
            <div class="inner">
                <h3>@Model.OrderCount</h3>

                <p>Orders</p>
            </div>
            <div class="icon">
                <i class="fas fa-cart-arrow-down"></i>
            </div>
            <a asp-controller="Orders" asp-action="Index" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-fuchsia">
            <div class="inner">
                <h3>@Model.UserCount</h3>

                <p>Users</p>
            </div>
            <div class="icon">
                <i class="fas fa-users"></i>
            </div>
            <a asp-controller="Users" asp-action="Index" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <!-- ./col -->
    <!--<div class="col-lg-3 col-6">-->
        <!-- small box -->
        <!--<div class="small-box bg-gradient-cyan">
            <div class="inner">
                <h3>0</h3>

                <p>Comments</p>
            </div>
            <div class="icon">
                <i class="fas fa-comments"></i>
            </div>
            <a asp-controller="Comments" asp-action="Index" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>-->
    <!-- ./col -->
</div>
<!-- /.row -->